spring.application.name=demo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:2020/demo_java_db
spring.datasource.username=vintermarco
spring.datasource.password=admin
jwt.secret=7QVQsVc8yFDxdY2+YNKuQCZcgAjE7TNXvDb0oWK6n4Y=
jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=update
